-- CRIAÇÃO DO BANCO
CREATE DATABASE IF NOT EXISTS sistema_vendas;
USE sistema_vendas;

-- TABELA CATEGORIA
CREATE TABLE IF NOT EXISTS categoria (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao TEXT,
    dataCriacao DATETIME DEFAULT CURRENT_TIMESTAMP,
    dataAtualizacao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    usuarioAtualizacao INT,
    ativo TINYINT(1) DEFAULT 1
);

